version: '3.8'
services:
  frontend:
    build: 
      context: ./client
    ports:
     - "3010:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
    - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "3011:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
