name: Run client Lint

on:
  push:
    paths:
      - 'client/**'

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome on client
        working-directory: ./client
        run: biome ci .

      - name: Run TypeScript check
        working-directory: ./client
        run: npm run lint:tsc
